name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Determine the version (tag or branch)
      - name: Determine version
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "::set-output name=VERSION::$VERSION"
            echo "::set-output name=IS_TAG::true"
          else
            VERSION=${GITHUB_REF#refs/heads/}
            echo "::set-output name=VERSION::$VERSION"
            echo "::set-output name=IS_TAG::false"
          fi

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      # Build and push Docker image with appropriate tags
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pocketbase-starter:latest
            ghcr.io/${{ github.repository_owner }}/pocketbase-starter:${{ steps.version.outputs.VERSION }}
